# Variables
@baseUrl=http://localhost:3333


# HealthCheck

Get {{baseUrl}}/health


###

# Get Rooms
GET {{baseUrl}}/rooms


###
# Create room
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala 01 de teste",
  "description": "Minha sala de teste"
}